[package]
name = "wareki-conv"
version = "0.1.0"
edition = "2021"
authors = ["kv5h"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
log = "0.4.20"
regex = "1.10.3"
unicode-jp = "0.4.0"
